In [1]:
import pandas as pd
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from tqdm import tqdm

tqdm.pandas()
stemmer = PorterStemmer()
lemmatizer=WordNetLemmatizer()

C:\Users\phoec\anaconda3\lib\site-packages\tqdm\std.py:658: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

## Directional Words

In [2]:
FILE_DIR = "./custom_lexicons/sentidd/"
DIRECTIONAL_WORDS_RAW_FILEPATH = FILE_DIR+'directional_words_raw.csv'
DIRECTIONAL_WORDS_FILEPATH = FILE_DIR+'directional_words.csv'

directional_words_df = pd.read_csv(DIRECTIONAL_WORDS_RAW_FILEPATH)
directional_words_df['stemmed'] = directional_words_df['token'].progress_apply(lambda x: stemmer.stem(x))
directional_words_df

100%|████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 6204.59it/s]

         token label    stemmed
0   accelerate    up    acceler
1      advance    up     advanc
2        award    up      award
3       better    up     better
4        climb    up      climb
5       double    up      doubl
6       faster    up     faster
7         gain    up       gain
8         grow    up       grow
9       higher    up     higher
10    increase    up    increas
11        jump    up       jump
12     quicken    up    quicken
13     rebound    up    rebound
14     recover    up      recov
15        rise    up       rise
16        rose    up       rose
17     step-up    up    step-up
18       surge    up       surg
19          up    up         up
20   constrain  down  constrain
21  decelerate  down    deceler
22     decline  down     declin
23    decrease  down    decreas
24        down  down       down
25        drop  down       drop
26        fall  down       fall
27        fell  down       fell
28      slower  down     slower
29      weaken  down     weaken
30      weaker  down     weaker

In [3]:
directional_words_df.to_csv(DIRECTIONAL_WORDS_FILEPATH, index=False)

## Loughran-McDonald Dictionary

In [4]:
LM_RAW_FILEPATH = "Loughran-McDonald_MasterDictionary_1993-2021.csv"
LM_FILEPATH = "LM_Word_List.csv"
lm_df = pd.read_csv(FILE_DIR+LM_RAW_FILEPATH)
lm_df

,Word,Seq_num,Word Count,Word Proportion,Average Proportion,Std Dev,Doc Count,Negative,Positive,Uncertainty,Litigious,Strong_Modal,Weak_Modal,Constraining,Syllables,Source
0,AARDVARK,1,354,1.550080e-08,1.422600e-08,3.815486e-06,99,0,0,0,0,0,0,0,2,12of12inf
1,AARDVARKS,2,3,1.313627e-10,8.653817e-12,9.241714e-09,1,0,0,0,0,0,0,0,2,12of12inf
2,ABACI,3,9,3.940882e-10,1.169679e-10,5.290465e-08,7,0,0,0,0,0,0,0,3,12of12inf
3,ABACK,4,29,1.269840e-09,6.654735e-10,1.595100e-07,28,0,0,0,0,0,0,0,2,12of12inf
4,ABACUS,5,8570,3.752595e-07,3.809464e-07,3.529356e-05,1108,0,0,0,0,0,0,0,3,12of12inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86526,ZYGOTE,86529,50,2.189379e-09,8.729336e-10,1.886011e-07,35,0,0,0,0,0,0,0,2,12of12inf
86527,ZYGOTES,86530,1,4.378757e-11,1.809516e-11,1.932446e-08,1,0,0,0,0,0,0,0,2,12of12inf
86528,ZYGOTIC,86531,0,0.000000e+00,0.000000e+00,0.000000e+00,0,0,0,0,0,0,0,0,3,12of12inf
86529,ZYMURGIES,86532,0,0.000000e+00,0.000000e+00,0.000000e+00,0,0,0,0,0,0,0,0,3,12of12inf
86530,ZYMURGY,86533,0,0.000000e+00,0.000000e+00,0.000000e+00,0,0,0,0,0,0,0,0,3,12of12inf

In [5]:
lexicon_df = lm_df.query('Negative != 0 | Positive != 0')
lexicon_df = lexicon_df[["Word", "Negative", "Positive"]]
lexicon_df

               Word  Negative  Positive
9           ABANDON      2009         0
10        ABANDONED      2009         0
11       ABANDONING      2009         0
12      ABANDONMENT      2009         0
13     ABANDONMENTS      2009         0
...             ...       ...       ...
86080    WRONGDOING      2009         0
86081   WRONGDOINGS      2009         0
86085      WRONGFUL      2009         0
86086    WRONGFULLY      2009         0
86094       WRONGLY      2009         0

[2709 rows x 3 columns]

In [6]:
len(lm_df[lm_df['Negative']!=0]) + len(lm_df[lm_df['Positive']!=0])

2709

In [7]:
lexicon_df["word"] = lexicon_df["Word"].str.lower()
lexicon_df["label"] = ["positive" if positive!=0 else "negative" for positive in lexicon_df["Positive"]]
lexicon_df = lexicon_df[["word","label"]]
lexicon_df

               word     label
9           abandon  negative
10        abandoned  negative
11       abandoning  negative
12      abandonment  negative
13     abandonments  negative
...             ...       ...
86080    wrongdoing  negative
86081   wrongdoings  negative
86085      wrongful  negative
86086    wrongfully  negative
86094       wrongly  negative

[2709 rows x 2 columns]

In [8]:
lexicon_df.to_csv(FILE_DIR+LM_FILEPATH, index=False)